// <auto-generated />
namespace sep24migrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class More_Subject_properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(More_Subject_properties));
        
        string IMigrationMetadata.Id
        {
            get { return "201309232252209_More_Subject_properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
