using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sep10v2.ViewModels
{
    // Choose unique names for the view model classes
    // Do not re-use the original class name (in the app domain data model)

    // All fields, flattened
    public class ProgramComplete
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public int Semesters { get; set; }
        public string Credential { get; set; }
    }

    // Just the fields that are useful for a drop-down list type of control
    public class ProgramList
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    // A template for adding a 'new' Program object
    // Notice that there's no 'Id' field, because that's auto-generated by the data store
    public class ProgramAdd
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Semesters { get; set; }
        public string Credential { get; set; }
    }

}
